Outdoorbuddies_root/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("outdoorbuddies.urls")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Outdoorbuddies_root/outdoorbuddies/urls.py
from django.urls import path
from .views import register, about, contact, create_adventure, adventure_detail, profile
from .views import join_adventure, delete_adventure, search_results, user_profile
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path("", views.index, name="index"),
    path("register/", register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='outdoorbuddies/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='outdoorbuddies/logout.html'), name='logout'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('create-adevnture/', create_adventure, name='create_adventure'),
    path('liked-adventures/', views.liked_adventures, name='liked_adventures'),
    path('like-adventure/<int:adventure_id>/', views.like_adventure, name='like_adventure'),
    path('adventures/<int:adventure_id>/', adventure_detail, name='adventure_detail'),
    path('profile/', profile, name='profile'),
    path('user/<str:username>/', user_profile, name='user_profile'),
    path('search/', search_results, name='search_results'),
    path('join-adventure/<int:adventure_id>/', join_adventure, name='join_adventure'),
    path('delete-adventure/<int:adventure_id>/', delete_adventure, name='delete_adventure'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='outdoorbuddies/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='outdoorbuddies/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='outdoorbuddies/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='outdoorbuddies/password_reset_complete.html'), name='password_reset_complete'),
]

Outdoorbuddies_root/outdoorbuddies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage

#tags include biking and hiking
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

#this model is the basis for creating posts for adventures
class Adventure(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='adventure_pics')
    description = models.TextField()
    max_participants = models.IntegerField()
    location = models.CharField(max_length=255)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    event_datetime = models.DateTimeField()
    likes = models.ManyToManyField(User, related_name='liked_adventures', blank=True)

    def __str__(self):
        return self.description
    
    def total_likes(self):
        return self.likes.count()

# comments on adventures
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    adventure = models.ForeignKey(Adventure, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def anonymize_user(self):
        self.user = None  
        self.save()

    def __str__(self):
        return self.text

#users can like adventures
class UserLikes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    adventure = models.ForeignKey(Adventure, on_delete=models.CASCADE)

#model to save participants
class AdventureParticipants(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    adventure = models.ForeignKey(Adventure, on_delete=models.CASCADE)
    is_host = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} - {self.adventure.description}'
    

#profile setup
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(upload_to='profile_photos', blank=True)
    bio = models.TextField(blank=True)
    interests = models.ManyToManyField(Tag, blank=True)  # Relation to Tag

    def profile_photo_url(self):
        if self.profile_photo and hasattr(self.profile_photo, 'url'):
            return self.profile_photo.url
        else:
            return staticfiles_storage.url('outdoorbuddies/images/default.jpg')  # Path to the default image

    def __str__(self):
        return f'{self.user.username} Profile'
    
#signals to instance a new profile for a new user
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
#saves the profile instance
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

Outdoorbuddies_root/outdoorbuddies/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Adventure, Comment, Tag

# user registration for a new user.
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# a form for someone to contact the site administrator
class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

# adventure form to create a new adventure
class AdventureForm(forms.ModelForm):
    class Meta:
        model = Adventure
        fields = ['picture', 'description', 'max_participants', 'location', 'tag', 'event_datetime']
        widgets = {
            'event_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }
#create a comment under adventure
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }
#profile editing form      
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_photo', 'bio', 'interests']
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 4}),
            'interests': forms.CheckboxSelectMultiple(),
        }
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['interests'].queryset = Tag.objects.all()

Outdoorbuddies_root/outdoorbuddies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegisterForm, ContactForm, AdventureForm, CommentForm, ProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from .models import Adventure, Comment, AdventureParticipants, Profile, User
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Q

#searching for users and adventures
def search_results(request):
    query = request.GET.get('q', '')
    profiles = Profile.objects.filter(
        Q(user__username__icontains=query)
    )
    adventures = Adventure.objects.filter(
        Q(description__icontains=query) | 
        Q(user__username__icontains=query) |
        Q(location__icontains=query)  # Add location-based filtering
    )
    return render(request, 'outdoorbuddies/search_results.html', {
        'profiles': profiles, 
        'adventures': adventures,
        'query': query
    })

#register a new user
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            # can add logic here to automatically log in the user
            return redirect('index')
    else:
        form = UserRegisterForm()
    return render(request, 'outdoorbuddies/register.html', {'form': form})

def index(request):
    # Fetch all adventure postings ordered by most recent
    adventures = Adventure.objects.all().order_by('-event_datetime')
    return render(request, 'outdoorbuddies/index.html', {'adventures': adventures})

#about us page used to describe outdoorbuddies
def about(request):
    return render(request, 'outdoorbuddies/about.html')

#displays a user profile
def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)

    # Get adventures posted by the user
    posted_adventures = Adventure.objects.filter(user=user)

    # Get adventures where the user is a participant
    participating_adventures = Adventure.objects.filter(adventureparticipants__user=user)

    # Combine both QuerySets into a single list, avoiding duplicates
    user_adventures = (posted_adventures | participating_adventures).distinct()

    return render(request, 'outdoorbuddies/user_profile.html', {
        'profile_user': user,
        'profile': profile,
        'user_adventures': user_adventures
    })

#contact us page view
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Process the form data
            name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']
            message = form.cleaned_data['message']

             # Compose the email message
            full_message = f"Sent by: {name}, Email: {sender_email}\n\n{message}"
            send_mail(
                subject=f'Message from {name}',  # subject
                message=full_message,  # message
                from_email='arcurry@alaska.edu',  # Use your default FROM email in Django settings
                recipient_list=['arcurry@alaska.edu'],  # to email
                fail_silently=False,
            )
            messages.success(request, 'Your message has been sent successfully!')
            return redirect('contact')  # Redirect to a success page
    else:
        form = ContactForm()

    return render(request, 'outdoorbuddies/contact.html', {'form': form})

#for each aventure 
def adventure_detail(request, adventure_id):
    adventure = get_object_or_404(Adventure, id=adventure_id)
    participants = AdventureParticipants.objects.filter(adventure=adventure)
    comments = Comment.objects.filter(adventure=adventure).order_by('-timestamp')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.adventure = adventure
            comment.save()
            return redirect('adventure_detail', adventure_id=adventure_id)
    else:
        comment_form = CommentForm()

    return render(request, 'outdoorbuddies/adventure_detail.html', {'adventure': adventure, 'participants' : participants, 'comments': comments, 'comment_form': comment_form})

#---------------------------------- login required ----------------------------------------------------

#adventure form creation
@login_required
def create_adventure(request):
    if request.method == 'POST':
        form = AdventureForm(request.POST, request.FILES)
        if form.is_valid():
            adventure = form.save(commit=False)
            adventure.user = request.user  # Set the current user as the creator of the adventure
            adventure.save()
            AdventureParticipants.objects.create(user=request.user, adventure=adventure, is_host=True)
            return redirect('adventure_detail', adventure.id)
    else:
        form = AdventureForm()

    return render(request, 'outdoorbuddies/create_adventure.html', {'form': form})

#remove adventure
@login_required
def delete_adventure(request, adventure_id):
    adventure = get_object_or_404(Adventure, id=adventure_id)

    # Check if the request user is the host
    if adventure.user == request.user:
        adventure.delete()
        messages.success(request, 'Adventure deleted successfully.')
        return HttpResponseRedirect(reverse('index'))  # Redirect to the home page
    else:
        messages.error(request, 'You do not have permission to delete this adventure.')
        return HttpResponseRedirect(reverse('adventure_detail', args=[adventure_id]))
    
# liking an adventure
@login_required
def liked_adventures(request):
    user = request.user
    adventures = user.liked_adventures.all()
    return render(request, 'outdoorbuddies/liked_adventures.html', {'adventures': adventures})

@login_required
def like_adventure(request, adventure_id):
    adventure = get_object_or_404(Adventure, id=adventure_id)
    if request.user in adventure.likes.all():
        adventure.likes.remove(request.user)
    else:
        adventure.likes.add(request.user)
    return redirect(reverse('adventure_detail', args=[adventure_id]))

@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile')
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    
    user_adventures = Adventure.objects.filter(user=request.user)
    return render(request, 'outdoorbuddies/profile.html', {'profile_form': profile_form, 'adventures': user_adventures})

@login_required
def join_adventure(request, adventure_id):
    adventure = get_object_or_404(Adventure, id=adventure_id)
    if not AdventureParticipants.objects.filter(user=request.user, adventure=adventure).exists():
        AdventureParticipants.objects.create(user=request.user, adventure=adventure)
    return redirect('adventure_detail', adventure_id=adventure.id)

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/adventure_detail.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <div class="content-container">
    <div class="adventure-detail-container">
      <div class="adventure-image">
        <img src="{{ adventure.picture.url }}" alt="Adventure Picture">
      </div>
      <div class="adventure-content">
        <h2 class="adventure-location-title">{{ adventure.location }}</h2>
        <p class="adventure-description">{{ adventure.description }}</p>
        <p>Date: {{ adventure.event_datetime|date:"d M Y H:i" }}</p>
        <p>Tags: {{ adventure.tag.name }}</p>
        <p>Likes: {{ adventure.total_likes }}</p>
        <p>Status: {{ adventure.status }}</p>
        <p>Max Participants: {{ adventure.max_participants }}</p>
        {% if user.is_authenticated %}
          <a href="{% url 'like_adventure' adventure.id %}">Like</a>
        {% endif %}
      </div>

      <h3>Participants</h3>
      <ul>
          {% for participant in participants %}
              <li>{{ participant.user.username }} {% if participant.is_host %}(host){% endif %}</li>
          {% empty %}
              <li>No participants yet.</li>
          {% endfor %}
      </ul>

      {% if user.is_authenticated and not user in adventure.adventureparticipants_set.all %}
          <a href="{% url 'join_adventure' adventure.id %}">Join this Adventure</a>
      {% endif %}

      {% if user == adventure.user %}
          <form action="{% url 'delete_adventure' adventure.id %}" method="post">
              {% csrf_token %}
              <button type="submit" onclick="return confirm('Are you sure you want to delete this adventure? This action cannot be undone.');">
                  Delete Adventure
              </button>
          </form>
      {% endif %}
      {% if user.is_authenticated %}
        <h3>Leave a comment</h3>
        <form method="post">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <button type="submit">Post Comment</button>
        </form>
      {% endif %}

      <div class="comments-section">
        <h3>Comments</h3>
        {% for comment in comments %}
          <div class="comment-box">
            <div class="comment-header">
              <span class="comment-user">{{ comment.user.username }}</span>
              <span class="comment-date">{{ comment.timestamp|date:"d M Y H:i" }}</span>
            </div>
            <p class="comment-text">{{ comment.text }}</p>
          </div>
        {% empty %}
          <p>No comments yet.</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Outdoor Buddies</title>
    <link rel="stylesheet" href="{% static 'outdoorbuddies/css/styles.css' %}">
       <!-- Include Leaflet CSS and JavaScript for OpenStreetMap -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar">
        <div class="navbar-buttons">
            <a class="nav-button" href="{% url 'index' %}">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-button" href="{% url 'liked_adventures' %}">Liked Adventures</a>
                <a class="nav-button" href="{% url 'create_adventure' %}">Create Adventure</a>
            {% else %}
                <a class="nav-button" href="{% url 'register' %}">Register</a>
            {% endif %}
            <form action="{% url 'search_results' %}" method="get">
                <input type="text" name="q" placeholder="Search...">
                <button type="submit">Search</button>
            </form>
        </div>
        {% if user.is_authenticated %}
            <div class="profile-info">
                <div class="profile-dropdown">
                    <img src="{{ user.profile.profile_photo_url }}" alt="Profile Photo" class="profile-photo-navbar">
                    <div class="profile-dropdown-content">
                        <a href="{% url 'profile' %}">Profile</a>
                        <a href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
                <span class="username">{{ user.username }}</span>
            </div>
        {% else %}
            <div class="sign-in">
                <a href="{% url 'login' %}" class="nav-button">Sign In</a>
            </div>
        {% endif %}
    </div>
    
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    
    <div class="footer">
        <a href="{% url 'about' %}">About</a>
        <a href="{% url 'contact' %}">Contact Us</a>
    </div>
</body>
</html>

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/create_adventure.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>Create Adventure</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Adventure</button>
  </form>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/index.html
{% extends 'outdoorbuddies/base.html' %}

{% load static %}
{% block content %}
  <h2>Latest Adventures</h2>
  <div class="content-container">
    <div class="adventure-listings">
      {% for adventure in adventures %}
        <a href="{% url 'adventure_detail' adventure.id %}" class="adventure-post-link">
          <div class="adventure-post">
              {% if adventure.picture %}
                  <img src="{{ adventure.picture.url }}" alt="Adventure Picture" class="adventure-photo">
              {% endif %}
              <div class="adventure-info">
                  <h3>{{ adventure.location }}</h3>
                  <p>{{ adventure.description }}</p>
                  <p>Time: {{ adventure.event_datetime|date:"d M Y H:i" }}</p>
                  <p>Participants: {{ adventure.max_participants }}</p>
              </div>
          </div>
        </a>
      {% empty %}
        <p>No adventures posted yet.</p>
      {% endfor %}
    </div>

    <div class="map-container">
      <div id="sidebar-map">Trail Details</div>
      <div id="map"></div>
    </div>
  </div>


  <script>
    var map = L.map('map').setView([61.2181, -149.9003], 10);  // Coordinates for Anchorage

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    // Load GeoJSON
    fetch("{% static 'outdoorbuddies/data/Anchorage_Muni_trails.geojson' %}")
        .then(response => response.json())
        .then(data => {
            L.geoJSON(data, {
              onEachFeature: function (feature, layer) {
                layer.on('click', function () {
                    var props = feature.properties;
                    var trailDetails = '<h3>' + (props.Trail_Name || 'Unknown Trail') + '</h3>';
                    trailDetails += '<p>Trail System: ' + (props.Trail_System || 'N/A') + '</p>';
                    trailDetails += '<p>Difficulty: ' + (props.Difficulty || 'N/A') + '</p>';

                    document.getElementById('sidebar-map').innerHTML = trailDetails;
                });
              }
            }).addTo(map);
        });
  </script>

{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/liked_adventures.html
{% extends 'outdoorbuddies/base.html' %}
{% load static %}
{% block content %}
  <h2>Liked Adventures</h2>
  <div class="content-container">
    <div class="adventure-listings">
      {% for adventure in adventures %}
        <a href="{% url 'adventure_detail' adventure.id %}" class="adventure-post-link">
          <div class="adventure-post">
              {% if adventure.picture %}
                  <img src="{{ adventure.picture.url }}" alt="Adventure Picture" class="adventure-photo">
              {% endif %}
              <div class="adventure-info">
                  <h3>{{ adventure.location }}</h3>
                  <p>{{ adventure.description }}</p>
                  <p>Time: {{ adventure.event_datetime|date:"d M Y H:i" }}</p>
                  <p>Participants: {{ adventure.max_participants }}</p>
              </div>
          </div>
        </a>
      {% empty %}
        <p>You haven't liked any adventures yet.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/login.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <p>Forgot Password? <a href="{% url 'password_reset' %}">Reset here</a>
  </p>

{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/logout.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>You have been logged out</h2>
  <a href="{% url 'login' %}">Login again?</a>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/password_reset.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>Password Reset</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send Password Reset Email</button>
  </form>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/password_reset_complete.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>Password Reset Complete</h2>
  <p>Your password has been set. You may now <a href="{% url 'login' %}">log in</a>.</p>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/password_reset_confirm.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>Reset Your Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change my password</button>
  </form>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/password_reset_done.html
{% extends 'outdoorbuddies/base.html' %}

{% block content %}
  <h2>Password Reset Sent</h2>
  <p>An email has been sent with instructions to reset your password.</p>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/register.html
{% extends 'outdoorbuddies/base.html' %}  <!-- Extend your base layout -->

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>

  Already have an account? <a href="{% url 'login' %}">Log In here.</a>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/search_results.html
{% extends 'outdoorbuddies/base.html' %}
{% load static %}
{% block content %}
  <div class="search-results-container">
    <h2>Search Results for "{{ query }}"</h2>

    <div class="results-columns">
      <div class="user-profiles-column">
        <h3>User Profiles</h3>
        {% for profile in profiles %}
            <a href="{% url 'user_profile' profile.user.username %}" class="user-profile-link">
                <div class="user-profile-box">
                    {% if profile.profile_photo %}
                        <img src="{{ profile.profile_photo.url }}" alt="{{ profile.user.username }}" class="profile-photo-search">
                    {% else %}
                        <img src="{% static 'outdoorbuddies/images/default.jpg' %}" alt="Default Profile Photo" class="profile-photo-search">
                    {% endif %}
                    <div class="username-search">{{ profile.user.username }}</div>
                </div>
            </a>
        {% empty %}
          <p>No profiles found.</p>
        {% endfor %}
      </div>

      <div class="adventures-column">
        <h3>Adventures</h3>
        {% for adventure in adventures %}
          <a href="{% url 'adventure_detail' adventure.id %}" class="adventure-post-link">
          <div class="adventure-post">
            {% if adventure.picture %}
              <img src="{{ adventure.picture.url }}" alt="Adventure Picture" class="adventure-photo">
            {% endif %}
            <div class="adventure-info">
              <h4>{{ adventure.location }}</h4>
              <p>{{ adventure.description }}</p>
              <p>Time: {{ adventure.event_datetime|date:"d M Y H:i" }}</p>
              <p>Participants: {{ adventure.max_participants }}</p>
            </div>
          </div>
        {% empty %}
          <p>No adventures found.</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

Outdoorbuddies_root/outdoorbuddies/templates/outdoorbuddies/user_profile.html
{% extends 'outdoorbuddies/base.html' %}
{% load static %}
{% block content %}
  <div class="profile-container">
    <div class="profile-sidebar">
      {% if profile.profile_photo %}
        <img src="{{ profile.profile_photo.url }}" alt="{{ profile_user.username }}'s Profile Picture" class="profile-photo">
      {% else %}
        <!-- Display a default image if profile_photo does not exist -->
        <img src="{% static 'outdoorbuddies/images/default.jpg' %}" alt="Default Profile Photo" class="profile-photo">
      {% endif %}
      <h2>{{ profile_user.username }}</h2>
      <p>{{ profile.bio }}</p>
      <div class="tags">
        {% for tag in profile.interests.all %}
          <span class="tag">{{ tag.name }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="profile-main-content">
      <h3>Adventures</h3>
      {% for adventure in user_adventures %}
        <div class="adventure-post">
          {% if adventure.picture %}
            <img src="{{ adventure.picture.url }}" alt="Adventure Picture" class="adventure-photo">
          {% endif %}
          <div class="adventure-info">
            <h4>{{ adventure.location }}</h4>
            <p>{{ adventure.description }}</p>
            <p>Time: {{ adventure.event_datetime|date:"d M Y H:i" }}</p>
            <p>Participants: {{ adventure.max_participants }}</p>
          </div>
        </div>
      {% empty %}
        <p>{{ profile_user.username }} has no adventures yet.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}